# Generated by Django 5.2.4 on 2025-08-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0002_alter_lesson_content'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(related_name='course', through='enrolments.Enrolment', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolment',
            unique_together={('student', 'course')},
        ),
    ]
