# Generated by Django 5.2.4 on 2025-08-20 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0004_alter_course_instructor_videosession'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosession',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor'),
        ),
    ]
